import type {
  SectionContent,
  HomeworkItem,
  McOption,
  WrittenRubric,
} from "./types";

const mcq: HomeworkItem[] = [
  {
    itemType: "mc",
    prompt:
      "A four-year-old who has always said 'went' suddenly starts saying 'goed' and 'runned,' even though no adult around her talks that way. Which conclusion best follows about how her mind handles language?",
    mcOptions: [
      {
        text: "Language is so complex that a few odd words tell us nothing about what's happening in her head.",
        credit: 0,
      },
      {
        text: "She isn't just copying speech; her mind has extracted the 'add -ed for past tense' rule and is over-applying it. Test it by checking whether she also says 'foots' and 'mouses,' whether the errors fade as she memorizes exceptions, and whether she applies -ed to a made-up verb you teach her.",
        credit: 1.0,
      },
      {
        text: "She probably picked up the rule somewhere; we could listen for where she heard it.",
        credit: 0.6,
      },
      {
        text: "She seems to be making some kind of grammar mistake.",
        credit: 0.3,
      },
    ],
    correctAnswer:
      "She isn't just copying speech; her mind has extracted the 'add -ed for past tense' rule and is over-applying it. Test it by checking whether she also says 'foots' and 'mouses,' whether the errors fade as she memorizes exceptions, and whether she applies -ed to a made-up verb you teach her.",
    explanation:
      "Top credit names a mechanism (rule extraction, not imitation) and three checkable tests; the 'too complex to say anything' option refuses to commit and earns zero. 'Goed' can't be copied because nobody says it — so it must be generated by a rule.",
  },
  {
    itemType: "mc",
    prompt:
      "Across many cultures and languages, babies babble the same range of sounds at around six months, then by their first birthday they start dropping the sounds that don't appear in the language spoken around them. Which lead is strongest?",
    mcOptions: [
      {
        text: "Babies seem to change their babbling over time.",
        credit: 0.3,
      },
      {
        text: "The infant brain starts open to every speech sound and then tunes itself to the input it hears, pruning unused distinctions. Test whether babies raised on two languages keep more sound contrasts, whether the drop-off lines up with which sounds appear in the home language, and whether early exposure to a foreign sound preserves the ability to hear it.",
        credit: 1.0,
      },
      {
        text: "Babbling probably narrows toward the native language; we could record more babies and watch.",
        credit: 0.6,
      },
      {
        text: "Babies are born already knowing only their native language's sounds and never had the others.",
        credit: 0,
      },
    ],
    correctAnswer:
      "The infant brain starts open to every speech sound and then tunes itself to the input it hears, pruning unused distinctions. Test whether babies raised on two languages keep more sound contrasts, whether the drop-off lines up with which sounds appear in the home language, and whether early exposure to a foreign sound preserves the ability to hear it.",
    explanation:
      "The richest lead names perceptual narrowing as the mechanism and three tests; the zero option is defeated by the data — the universal early babbling shows the contrasts were present and then lost, not absent from birth.",
  },
  {
    itemType: "mc",
    prompt:
      "Russian has two everyday words for blue — 'goluboy' (light blue) and 'siniy' (dark blue) — with no single word for 'blue.' In a speeded task, Russian speakers tell apart shades that straddle that boundary faster than English speakers do. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Color and language are too tangled to draw any conclusion from a reaction-time gap.",
        credit: 0,
      },
      {
        text: "Having separate labels likely sharpens attention at that boundary, giving a small perceptual edge. Test whether the Russian advantage vanishes when speakers do a distracting verbal task, whether it's largest exactly at the goluboy/siniy line and not elsewhere, and whether English speakers trained on two blue words gain the same edge.",
        credit: 1.0,
      },
      {
        text: "Russian speakers seem a bit quicker with blue shades.",
        credit: 0.3,
      },
      {
        text: "The blue words probably help; we could test more Russian speakers.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Having separate labels likely sharpens attention at that boundary, giving a small perceptual edge. Test whether the Russian advantage vanishes when speakers do a distracting verbal task, whether it's largest exactly at the goluboy/siniy line and not elsewhere, and whether English speakers trained on two blue words gain the same edge.",
    explanation:
      "Top credit commits to a focused linguistic-relativity mechanism with three sharp tests, including a verbal-interference check; 'too tangled to conclude' opens no inquiry and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "In a community of deaf children brought together in Nicaragua who had no shared language, the youngest children spontaneously developed a sign system with consistent word order and grammatical structure richer than what the older arrivals used. Which lead opens the most inquiry?",
    mcOptions: [
      {
        text: "The children probably copied grammar from the hearing adults around them; we could check the adults' gestures.",
        credit: 0.6,
      },
      {
        text: "When given even thin raw material, young minds impose grammatical structure on it — the drive to build language is in the learner, not just the input. Test whether each new cohort of young children adds structure the older signers lack, whether the regularities appear without any structured adult model, and whether the same pattern shows up in other newly formed deaf communities.",
        credit: 1.0,
      },
      {
        text: "The deaf children seem to have made up their own signs.",
        credit: 0.3,
      },
      {
        text: "Language emergence is too rare and messy to learn anything general from one community.",
        credit: 0,
      },
    ],
    correctAnswer:
      "When given even thin raw material, young minds impose grammatical structure on it — the drive to build language is in the learner, not just the input. Test whether each new cohort of young children adds structure the older signers lack, whether the regularities appear without any structured adult model, and whether the same pattern shows up in other newly formed deaf communities.",
    explanation:
      "The productive lead names a learner-driven structuring mechanism with three tests; 'too rare to learn anything' is the barren dodge. The fact that the youngest added the most structure defeats the 'copied from adults' rival.",
  },
  {
    itemType: "mc",
    prompt:
      "Children master complicated grammar — like forming questions and using pronouns correctly — by age four, even though the speech they hear is full of false starts, slang, and incomplete sentences, and adults rarely correct their grammar. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Kids just memorize all the sentences they hear and repeat them.",
        credit: 0,
      },
      {
        text: "The mind must bring built-in biases about how language works, letting children infer rules from messy input far faster than pure memorizing could. Test whether children produce correct sentences they could never have heard, whether grammar develops on a similar timetable across very different languages, and whether the same milestones appear despite huge differences in how much adults talk to kids.",
        credit: 1.0,
      },
      {
        text: "Children seem to learn grammar quickly.",
        credit: 0.3,
      },
      {
        text: "Children probably have some help learning grammar; we could survey how parents teach it.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "The mind must bring built-in biases about how language works, letting children infer rules from messy input far faster than pure memorizing could. Test whether children produce correct sentences they could never have heard, whether grammar develops on a similar timetable across very different languages, and whether the same milestones appear despite huge differences in how much adults talk to kids.",
    explanation:
      "Top credit names the poverty-of-the-stimulus argument as a mechanism with three tests; the 'just memorize' option is defeated because children produce novel sentences and the input is too thin to copy from.",
  },
  {
    itemType: "mc",
    prompt:
      "Speakers of an Australian language, Guugu Yimithirr, don't use 'left' and 'right.' They describe everything by compass direction ('the cup north of the plate'). These speakers are remarkably good at pointing to true north even in unfamiliar places. Which lead is strongest?",
    mcOptions: [
      {
        text: "Spatial skill is too personal to connect to the words a group happens to use.",
        credit: 0,
      },
      {
        text: "Constantly encoding directions in speech likely forces speakers to keep a running mental compass, training their spatial tracking. Test whether the advantage holds for speakers spun around indoors with no landmarks, whether children gain the skill as they master the direction words, and whether speakers of left/right languages who train in compass terms catch up.",
        credit: 1.0,
      },
      {
        text: "These speakers seem to have a good sense of direction.",
        credit: 0.3,
      },
      {
        text: "Their language probably helps navigation; we could test more speakers outdoors.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Constantly encoding directions in speech likely forces speakers to keep a running mental compass, training their spatial tracking. Test whether the advantage holds for speakers spun around indoors with no landmarks, whether children gain the skill as they master the direction words, and whether speakers of left/right languages who train in compass terms catch up.",
    explanation:
      "The richest lead names a habitual-encoding mechanism and three tests, including a training check that could refute it; 'too personal to connect' refuses to lead and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "A community studied by researchers uses only the number words 'one,' 'two,' and 'many.' When asked to lay out the same number of nuts as the experimenter for quantities above three, members make more errors as the count grows. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Number sense is too deep and universal for word choice to matter at all.",
        credit: 0,
      },
      {
        text: "Counting words seem related to matching quantities.",
        credit: 0.3,
      },
      {
        text: "Exact-number words likely act as mental tags that let people hold a precise count, so without them the mind falls back on rough estimation that drifts as numbers grow. Test whether errors scale with quantity (a signature of estimation), whether members taught counting words improve, and whether they still handle small sets of one to three perfectly.",
        credit: 1.0,
      },
      {
        text: "The missing number words probably cause the errors; we could test bigger groups.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Exact-number words likely act as mental tags that let people hold a precise count, so without them the mind falls back on rough estimation that drifts as numbers grow. Test whether errors scale with quantity (a signature of estimation), whether members taught counting words improve, and whether they still handle small sets of one to three perfectly.",
    explanation:
      "Top credit names number words as cognitive tools with three tests, including the error-scaling signature; the 'word choice can't matter' option is defeated by the very pattern of growing errors.",
  },
  {
    itemType: "mc",
    prompt:
      "People who learn a second language after about puberty almost always keep an accent and struggle with fine grammar, while those who start young usually become fully fluent — even for two learners with the same years of practice. Which lead opens the most inquiry?",
    mcOptions: [
      {
        text: "Language ability is too variable across people to blame the age someone started.",
        credit: 0,
      },
      {
        text: "Older learners seem to have a harder time.",
        credit: 0.3,
      },
      {
        text: "The brain likely has a sensitive period when language circuits are most flexible, after which they lose plasticity. Test whether outcome tracks age-of-first-exposure more tightly than years of practice, whether immigrants who arrived as children outperform same-duration adult arrivals, and whether brain imaging shows different processing for early versus late learners.",
        credit: 1.0,
      },
      {
        text: "Starting young probably helps; we could compare more learners over time.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "The brain likely has a sensitive period when language circuits are most flexible, after which they lose plasticity. Test whether outcome tracks age-of-first-exposure more tightly than years of practice, whether immigrants who arrived as children outperform same-duration adult arrivals, and whether brain imaging shows different processing for early versus late learners.",
    explanation:
      "The productive lead names a critical-period mechanism and three tests that separate age from practice; 'too variable to blame age' commits to nothing and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "When English speakers hear a continuous slide of sound from 'ba' to 'pa,' they don't hear a smooth blend — they hear clear 'ba' until a sudden flip to clear 'pa,' with almost no in-between. Sounds on the same side of that line are hard to tell apart; sounds across it are easy. Which conclusion best follows?",
    mcOptions: [
      {
        text: "The mind probably sorts the sound stream into a small set of speech categories, so it sharpens differences across a category line and blurs them within. Test whether the boundary shifts for speakers of a language that splits those sounds differently, whether infants show the boundary before they speak, and whether the within-category blurring disappears for non-speech tones.",
        credit: 1.0,
      },
      {
        text: "People seem to hear 'ba' and 'pa' as different.",
        credit: 0.3,
      },
      {
        text: "Hearing is too subjective to read anything into where people place a sound boundary.",
        credit: 0,
      },
      {
        text: "The mind probably groups the sounds; we could play the slide to more listeners.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "The mind probably sorts the sound stream into a small set of speech categories, so it sharpens differences across a category line and blurs them within. Test whether the boundary shifts for speakers of a language that splits those sounds differently, whether infants show the boundary before they speak, and whether the within-category blurring disappears for non-speech tones.",
    explanation:
      "Top credit names categorical perception as the mechanism with three tests, including a cross-language and a non-speech control; 'too subjective' refuses to lead and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "Reading the sentence 'The old man the boats,' most people stumble — they first read 'old man' as a person, then have to back up when 'the boats' has no verb, and reparse 'man' as the verb. Which lead is strongest?",
    mcOptions: [
      {
        text: "Reading hiccups are too random to tell us anything about how the mind works.",
        credit: 0,
      },
      {
        text: "The mind likely builds sentence meaning word-by-word in real time, committing early to the most common reading and paying a cost when it must reparse. Test whether eye-tracking shows readers slow and look back right at 'boats,' whether the stumble shrinks when context primes the rare meaning first, and whether sentences without a misleading early reading cause no slowdown.",
        credit: 1.0,
      },
      {
        text: "People seem to get confused by that sentence.",
        credit: 0.3,
      },
      {
        text: "The sentence probably trips readers up; we could try it on more people.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "The mind likely builds sentence meaning word-by-word in real time, committing early to the most common reading and paying a cost when it must reparse. Test whether eye-tracking shows readers slow and look back right at 'boats,' whether the stumble shrinks when context primes the rare meaning first, and whether sentences without a misleading early reading cause no slowdown.",
    explanation:
      "The richest lead names incremental parsing as the mechanism with three eye-tracking and context tests; 'too random to tell us anything' is the empty dodge.",
  },
  {
    itemType: "mc",
    prompt:
      "A patient after a stroke speaks in short, effortful, telegraphic phrases ('want... coffee... cup') but understands what others say. A different patient speaks fluently and grammatically but produces nonsense words and can't follow conversation. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Brains differ so much that two patients can't reveal anything general about language.",
        credit: 0,
      },
      {
        text: "Language likely isn't one lump but separable subsystems — roughly, building grammatical speech versus mapping words to meaning — handled by different brain regions. Test whether the two patients' damage sits in different, predictable areas, whether the production-impaired patient's comprehension stays intact on grammar tests, and whether the pattern repeats across many similar patients.",
        credit: 1.0,
      },
      {
        text: "The two patients seem to have different language problems.",
        credit: 0.3,
      },
      {
        text: "Language is probably split in the brain; we could scan more patients.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Language likely isn't one lump but separable subsystems — roughly, building grammatical speech versus mapping words to meaning — handled by different brain regions. Test whether the two patients' damage sits in different, predictable areas, whether the production-impaired patient's comprehension stays intact on grammar tests, and whether the pattern repeats across many similar patients.",
    explanation:
      "Top credit reads the double dissociation as evidence for separable language systems with three tests; 'can't reveal anything general' refuses to commit and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "When researchers survey color words across hundreds of languages, those with only a few color terms always have words for black and white, the next added is almost always red, then green/yellow, then blue — the same order again and again. Which lead opens the most inquiry?",
    mcOptions: [
      {
        text: "Color naming seems to follow some pattern.",
        credit: 0.3,
      },
      {
        text: "Languages can carve up color any way at all, so the shared order is just coincidence.",
        credit: 0,
      },
      {
        text: "Shared features of the human visual system likely make some color categories more salient, so languages tend to name them first in a similar order. Test whether the 'focal' shade people pick for each term is consistent across languages, whether the naming order matches which contrasts the eye detects most strongly, and whether infants who can't talk still group colors at those same focal points.",
        credit: 1.0,
      },
      {
        text: "Vision probably shapes color words; we could survey even more languages.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Shared features of the human visual system likely make some color categories more salient, so languages tend to name them first in a similar order. Test whether the 'focal' shade people pick for each term is consistent across languages, whether the naming order matches which contrasts the eye detects most strongly, and whether infants who can't talk still group colors at those same focal points.",
    explanation:
      "The productive lead grounds the universal order in shared perception with three tests; the 'just coincidence' option is defeated by the regularity itself — pure chance wouldn't repeat the same order across hundreds of languages.",
  },
  {
    itemType: "mc",
    prompt:
      "An 18-month-old who knows the word 'ball' is shown a ball and a strange gadget she's never seen. An adult says 'Look, a dax!' She immediately looks at the gadget, not the ball. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Toddlers learn words too unpredictably to read anything into one choice.",
        credit: 0,
      },
      {
        text: "She seems to know the new word goes with the new object.",
        credit: 0.3,
      },
      {
        text: "The child likely uses a built-in assumption that a new word maps to the unnamed object, which would speed word learning by ruling out known things. Test whether children without a familiar competitor object guess less reliably, whether the bias is weaker in bilinguals who routinely have two words per thing, and whether it predicts the words children actually pick up first.",
        credit: 1.0,
      },
      {
        text: "She probably guessed the new word's meaning; we could try more toddlers.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "The child likely uses a built-in assumption that a new word maps to the unnamed object, which would speed word learning by ruling out known things. Test whether children without a familiar competitor object guess less reliably, whether the bias is weaker in bilinguals who routinely have two words per thing, and whether it predicts the words children actually pick up first.",
    explanation:
      "Top credit names the mutual-exclusivity bias as a learning shortcut with three tests, including a bilingual prediction; 'too unpredictable to read anything' is the barren refusal.",
  },
  {
    itemType: "mc",
    prompt:
      "German speakers, whose word for 'bridge' is grammatically feminine, tend to describe bridges as 'elegant' and 'slender,' while Spanish speakers, whose word for 'bridge' is masculine, call them 'strong' and 'sturdy' — for the very same bridges. Which lead is strongest?",
    mcOptions: [
      {
        text: "Grammatical gender likely nudges how speakers think about objects by linking them to gender-associated traits, biasing description. Test whether the effect appears even when speakers are tested in a neutral third language, whether it shrinks for objects whose gender differs between the two languages, and whether speakers shown the object without naming it describe it the same way regardless of native tongue.",
        credit: 1.0,
      },
      {
        text: "Gender words seem to color how people describe things.",
        credit: 0.3,
      },
      {
        text: "Description is too much a matter of taste to link to a grammar feature.",
        credit: 0,
      },
      {
        text: "Grammatical gender probably affects descriptions; we could ask more speakers.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Grammatical gender likely nudges how speakers think about objects by linking them to gender-associated traits, biasing description. Test whether the effect appears even when speakers are tested in a neutral third language, whether it shrinks for objects whose gender differs between the two languages, and whether speakers shown the object without naming it describe it the same way regardless of native tongue.",
    explanation:
      "Top credit names a gender-association mechanism with three tests, including a neutral-language control; 'too much a matter of taste' refuses to lead and earns zero.",
  },
  {
    itemType: "mc",
    prompt:
      "Infants who hear a two-minute stream of nonsense syllables with no pauses (like 'bidakupadotigolabu...') can later tell apart 'words' that always occurred together from random three-syllable strings — even though there were no gaps marking the words. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Babies seem able to find patterns in sound.",
        credit: 0.3,
      },
      {
        text: "Infant minds probably track which sounds reliably follow which others, using those statistics to carve a continuous stream into word-like chunks. Test whether babies fail when the syllable transitions are made equally likely, whether the same statistical skill shows up for tone or visual sequences, and whether stronger transition-tracking predicts faster vocabulary growth later.",
        credit: 1.0,
      },
      {
        text: "Hearing is too murky in infants to conclude they're doing real computation.",
        credit: 0,
      },
      {
        text: "Babies probably notice the repeated sounds; we could test more infants.",
        credit: 0.6,
      },
    ],
    correctAnswer:
      "Infant minds probably track which sounds reliably follow which others, using those statistics to carve a continuous stream into word-like chunks. Test whether babies fail when the syllable transitions are made equally likely, whether the same statistical skill shows up for tone or visual sequences, and whether stronger transition-tracking predicts faster vocabulary growth later.",
    explanation:
      "The richest lead names statistical learning of transition probabilities with three tests, including a flat-statistics control; 'too murky to conclude' is the empty dodge.",
  },
];

const hybrid: HomeworkItem[] = [
  {
    itemType: "hybrid",
    prompt:
      "In the classic 'wug test,' a child is shown a drawing of an imaginary bird and told 'This is a wug.' Shown two, she is asked 'Now there are two ___?' Most preschoolers, who have never heard the word, say 'wugs.' Which lead best follows?",
    mcOptions: [
      {
        text: "The child can't have memorized 'wugs,' so she must have an internal plural rule she applies to brand-new words. Test whether she adds the right sound for tricky endings (saying 'wuzzes' for a 'wuz'), whether younger children fail before a certain age, and whether the same rule-extension shows up for made-up verbs and past tense.",
        credit: 1.0,
      },
      {
        text: "Kids seem to know how to make plurals.",
        credit: 0.3,
      },
      {
        text: "Word learning is too individual to conclude anything from one made-up word.",
        credit: 0,
      },
      {
        text: "She probably learned plurals somehow; we could test more children.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'internal plural rule' lead from the rival 'she's just imitating a memorized pattern,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: ask her to pluralize several novel words she has never possibly heard, including one needing the '-es' sound like 'tass' — if she has a rule, she'll produce 'tasses' with the correct sound she was never taught. My lead is refuted if she can only pluralize real, familiar words and freezes or guesses randomly on the made-up ones, which would point to memorization rather than a rule.",
      yieldAnchors: [
        "The child has never heard the word 'wug'",
        "She produces 'wugs' correctly",
        "Most preschoolers do this",
      ],
      riskAnchors: [
        "She adds the right '-es' sound for tricky endings on novel words",
        "Younger children fail before a certain age",
        "The same rule-extension appears for made-up past-tense verbs",
      ],
      defeatedBy: [
        "She can only handle memorized real words",
        "Plural use is unrelated to having any rule",
      ],
    },
    correctAnswer:
      "The child can't have memorized 'wugs,' so she must have an internal plural rule she applies to brand-new words. Test whether she adds the right sound for tricky endings (saying 'wuzzes' for a 'wuz'), whether younger children fail before a certain age, and whether the same rule-extension shows up for made-up verbs and past tense.",
    explanation:
      "Full credit commits to a productive-rule mechanism, spawns three checks, and pairs them with a novel-word test that names its own refutation; 'too individual to conclude' opens nothing.",
  },
  {
    itemType: "hybrid",
    prompt:
      "Brain scans show that deaf people using sign language activate many of the same left-hemisphere regions that hearing people use for spoken language — including areas tied to grammar — even though signing uses the hands and eyes, not the mouth and ears. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Brain imaging is too coarse to claim sign and speech share machinery.",
        credit: 0,
      },
      {
        text: "Signers seem to use language areas too.",
        credit: 0.3,
      },
      {
        text: "The brain's language system is likely organized around abstract grammar and meaning, not the specific channel (sound vs. sight), so any structured language can recruit it. Test whether sign-language damage to those areas causes grammar errors like spoken aphasia, whether the regions track grammatical complexity in signs, and whether late sign learners show the same late-learner processing differences as late speakers.",
        credit: 1.0,
      },
      {
        text: "Sign probably uses language regions; we could scan more signers.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'channel-independent language system' lead from the rival 'those regions just do any complex hand or visual task,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: compare brain activity when signers produce grammatical sentences versus when they make equally complex non-language hand gestures — my lead predicts the language regions light up far more for true signing. It is refuted if meaningless complex gestures activate those regions just as strongly, showing the areas respond to hand movement in general rather than to language.",
      yieldAnchors: [
        "Signing activates the same left-hemisphere language regions as speech",
        "Those regions include grammar-related areas",
        "Signing uses hands and eyes, not mouth and ears",
      ],
      riskAnchors: [
        "Damage to those areas causes sign-grammar errors like aphasia",
        "The regions track grammatical complexity in signs",
        "Late sign learners show late-learner processing differences",
      ],
      defeatedBy: [
        "The regions fire equally for non-language complex gestures",
        "Sign and speech share no neural machinery",
      ],
    },
    correctAnswer:
      "The brain's language system is likely organized around abstract grammar and meaning, not the specific channel (sound vs. sight), so any structured language can recruit it. Test whether sign-language damage to those areas causes grammar errors like spoken aphasia, whether the regions track grammatical complexity in signs, and whether late sign learners show the same late-learner processing differences as late speakers.",
    explanation:
      "Top credit reads the shared activation as a channel-independent grammar system with three tests and a gesture-control comparison that names its refutation; 'too coarse to claim' refuses to lead.",
  },
  {
    itemType: "hybrid",
    prompt:
      "English marks the future with words like 'will' ('it will rain'), while some languages use the same form for present and future ('it rains tomorrow'). One study reported that speakers of the no-future-marker languages saved more money and smoked less. Which lead is strongest?",
    mcOptions: [
      {
        text: "Grammar and behavior are too far apart to credit a verb form for savings rates.",
        credit: 0,
      },
      {
        text: "Not grammatically separating the future may make it feel closer and more like the present, nudging people to act for it — but culture is a strong rival, so the link needs careful testing. Test whether the effect survives comparing neighbors who share a culture but differ in language, whether it holds within bilingual individuals depending on which language they use, and whether matched economic and religious factors erase the gap.",
        credit: 1.0,
      },
      {
        text: "Future-marking languages seem tied to spending more.",
        credit: 0.3,
      },
      {
        text: "Grammar probably affects saving; we could compare more countries.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'grammar nudges time perception' lead from the rival 'shared culture, not grammar, drives both the language and the saving,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: compare savings among people from the same country and culture who differ only in which language they grew up speaking — if grammar matters, the language difference should still predict saving with culture held constant. My lead is refuted if, once culture and economics are matched, the language gap disappears, which would show culture was doing the work all along.",
      yieldAnchors: [
        "Some languages grammatically mark the future, others don't",
        "No-future-marker speakers reportedly saved more",
        "They also reportedly smoked less",
      ],
      riskAnchors: [
        "The effect survives comparing same-culture neighbors who differ in language",
        "It holds within bilinguals by language used",
        "Matched economic and religious factors don't erase it",
      ],
      defeatedBy: [
        "Matching culture and economics erases the gap",
        "Grammar is unrelated to saving behavior",
      ],
    },
    correctAnswer:
      "Not grammatically separating the future may make it feel closer and more like the present, nudging people to act for it — but culture is a strong rival, so the link needs careful testing. Test whether the effect survives comparing neighbors who share a culture but differ in language, whether it holds within bilingual individuals depending on which language they use, and whether matched economic and religious factors erase the gap.",
    explanation:
      "Full credit commits to a time-perception mechanism while naming the confound and three tests that could refute it; 'too far apart to credit' opens no inquiry and 'seems tied to spending more' names no mechanism.",
  },
  {
    itemType: "hybrid",
    prompt:
      "Asked to arrange picture cards of someone aging from young to old, English speakers lay them left-to-right, Hebrew speakers right-to-left, and speakers of a language that uses compass directions for time lay them east-to-west regardless of which way they're facing. Which conclusion best follows?",
    mcOptions: [
      {
        text: "How we picture time is likely shaped by the habits our language gives us for talking about space and order, so different languages produce different mental timelines. Test whether the layout flips when speakers are rotated to face a new direction, whether children adopt the pattern as they learn the relevant words, and whether bilinguals switch timelines depending on which language they're cued in.",
        credit: 1.0,
      },
      {
        text: "People from different languages seem to arrange time differently.",
        credit: 0.3,
      },
      {
        text: "Time is a universal feeling, so language can't possibly change how anyone pictures it.",
        credit: 0,
      },
      {
        text: "Language probably shapes the timeline; we could test more language groups.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'language shapes the mental timeline' lead from the rival 'people just copy their writing direction in the moment,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: test the compass-direction speakers, who have no fixed writing direction, by rotating them to face different ways — my lead predicts their timeline tracks east-to-west in the world, not their body or any script. It is refuted if everyone's arrangement simply follows the direction of their script and the compass-speakers show no consistent world-based ordering, pointing to writing habit alone.",
      yieldAnchors: [
        "English speakers arrange time left-to-right",
        "Hebrew speakers arrange it right-to-left",
        "Compass-direction speakers arrange it east-to-west regardless of facing",
      ],
      riskAnchors: [
        "The layout flips when speakers are rotated to face a new direction",
        "Children adopt the pattern as they learn the words",
        "Bilinguals switch timelines by language cue",
      ],
      defeatedBy: [
        "Everyone simply copies their script direction in the moment",
        "Mental timelines are identical across all languages",
      ],
    },
    correctAnswer:
      "How we picture time is likely shaped by the habits our language gives us for talking about space and order, so different languages produce different mental timelines. Test whether the layout flips when speakers are rotated to face a new direction, whether children adopt the pattern as they learn the relevant words, and whether bilinguals switch timelines depending on which language they're cued in.",
    explanation:
      "Top credit commits to a spatial-language mechanism with three tests, including the rotation test that names its refutation; 'language can't possibly change it' is defeated by the cross-language differences themselves.",
  },
  {
    itemType: "hybrid",
    prompt:
      "A bilingual cashier who grew up speaking two languages switches mid-sentence between them when chatting with bilingual customers, but never mixes the grammar — she switches only at points where both languages' grammar allow it, never producing a broken hybrid sentence. Which lead is strongest?",
    mcOptions: [
      {
        text: "Bilingual speech is too freewheeling to find any rule in.",
        credit: 0,
      },
      {
        text: "Her switching is rule-governed, suggesting both grammars are active at once and she switches only where the structures line up. Test whether other bilinguals switch at the same kinds of points, whether forbidden switch points (mid-phrase) almost never occur in recordings, and whether reaction times rise slightly at each switch as both systems coordinate.",
        credit: 1.0,
      },
      {
        text: "She seems to mix her languages smoothly.",
        credit: 0.3,
      },
      {
        text: "Her switching probably follows some pattern; we could record more of it.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'rule-governed switching with both grammars active' lead from the rival 'she switches randomly whenever a word comes to mind,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: record many of her switches and check whether they cluster at grammatically compatible boundaries and almost never break a phrase apart — my lead predicts switches obey both languages' structure. It is refuted if switches fall randomly across sentence positions, including ungrammatical mid-phrase spots, which would show no shared structural control.",
      yieldAnchors: [
        "She switches languages mid-sentence",
        "She never produces a broken hybrid sentence",
        "She switches only where both grammars allow",
      ],
      riskAnchors: [
        "Other bilinguals switch at the same kinds of points",
        "Forbidden mid-phrase switches almost never occur",
        "Reaction times rise slightly at each switch",
      ],
      defeatedBy: [
        "Switches fall randomly across all sentence positions",
        "Code-switching follows no grammatical constraint",
      ],
    },
    correctAnswer:
      "Her switching is rule-governed, suggesting both grammars are active at once and she switches only where the structures line up. Test whether other bilinguals switch at the same kinds of points, whether forbidden switch points (mid-phrase) almost never occur in recordings, and whether reaction times rise slightly at each switch as both systems coordinate.",
    explanation:
      "Full credit names dual-grammar coordination with three checks and a distribution test that names its refutation; 'too freewheeling to find a rule' is the barren dodge.",
  },
  {
    itemType: "hybrid",
    prompt:
      "Children can understand and produce sentences with one clause nested inside another — 'The dog that the cat that the girl fed chased ran away' is hard, but 'The boy who lives next door has a bike' is easy, and they readily handle one level of nesting they've never heard before. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Sentence complexity is too messy to draw conclusions about mental structure.",
        credit: 0,
      },
      {
        text: "Kids seem to handle some nested sentences but not others.",
        credit: 0.3,
      },
      {
        text: "The mind likely builds language with rules that can embed structures inside structures (recursion), but working memory limits how many levels it can hold. Test whether errors rise sharply with each added level of nesting, whether comprehension improves when memory load is eased (e.g., naming the actors), and whether the same one-level recursion appears across very different languages.",
        credit: 1.0,
      },
      {
        text: "Nesting probably strains the mind; we could test more sentence types.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'recursion plus memory-limit' lead from the rival 'kids only handle exact sentences they've memorized,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: give children brand-new one-level-nested sentences they could never have heard and see whether they understand them while still failing the deeply nested ones — my lead predicts success on novel single nesting and breakdown only as levels stack. It is refuted if children can only handle familiar memorized frames and fail every novel nested sentence, pointing to memorization rather than a recursive rule.",
      yieldAnchors: [
        "One level of nesting is easy",
        "Deeply nested sentences are very hard",
        "Children handle novel one-level nesting they've never heard",
      ],
      riskAnchors: [
        "Errors rise sharply with each added level of nesting",
        "Easing memory load improves comprehension",
        "One-level recursion appears across very different languages",
      ],
      defeatedBy: [
        "Children only handle memorized sentence frames",
        "Nesting difficulty is unrelated to memory load",
      ],
    },
    correctAnswer:
      "The mind likely builds language with rules that can embed structures inside structures (recursion), but working memory limits how many levels it can hold. Test whether errors rise sharply with each added level of nesting, whether comprehension improves when memory load is eased (e.g., naming the actors), and whether the same one-level recursion appears across very different languages.",
    explanation:
      "Top credit separates a recursive grammar from a memory bottleneck with three tests and a novel-sentence test that names its refutation; 'too messy to conclude' refuses to lead.",
  },
  {
    itemType: "hybrid",
    prompt:
      "Bilingual children are sometimes a little slower to name pictures and have smaller vocabularies in each single language, yet they tend to do better on tasks that require ignoring distractions and switching rules. Which lead is strongest?",
    mcOptions: [
      {
        text: "Constantly managing two languages — keeping one active while suppressing the other — likely trains the brain's general control system, with a small naming cost from splitting vocabulary. Test whether the control advantage scales with how often a child switches languages, whether the naming lag shrinks when both languages' words are counted together, and whether monolinguals trained on heavy task-switching close the control gap.",
        credit: 1.0,
      },
      {
        text: "Bilingual kids seem to have some strengths and some weaknesses.",
        credit: 0.3,
      },
      {
        text: "The mind is too variable to link bilingualism to any thinking skill.",
        credit: 0,
      },
      {
        text: "Bilingualism probably affects thinking; we could test more children.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'language-control trains general control' lead from the rival 'bilingual kids differ for unrelated reasons like family background,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: within bilinguals from similar backgrounds, check whether those who switch languages most often show the biggest control advantage — my lead predicts a dose-response link between switching and control. It is refuted if control skill is unrelated to how much a child actually switches, or vanishes once family background is matched, pointing to confounds rather than language control.",
      yieldAnchors: [
        "Bilinguals are slightly slower naming pictures",
        "They have smaller vocabularies in each single language",
        "They do better at ignoring distractions and switching rules",
      ],
      riskAnchors: [
        "The control advantage scales with how often the child switches",
        "The naming lag shrinks when both vocabularies are combined",
        "Monolinguals trained on task-switching close the gap",
      ],
      defeatedBy: [
        "Family background, not language, explains the differences",
        "Bilingualism has no link to control skills",
      ],
    },
    correctAnswer:
      "Constantly managing two languages — keeping one active while suppressing the other — likely trains the brain's general control system, with a small naming cost from splitting vocabulary. Test whether the control advantage scales with how often a child switches languages, whether the naming lag shrinks when both languages' words are counted together, and whether monolinguals trained on heavy task-switching close the control gap.",
    explanation:
      "Full credit names a control-training mechanism that explains both the cost and the benefit, with three tests and a dose-response check that names its refutation; 'too variable to link' opens nothing.",
  },
  {
    itemType: "hybrid",
    prompt:
      "In a remote group whose language has rich words for kinds of snow and ice but few abstract color words, members sort photos of icy landscapes into far finer categories than visiting researchers do, while sorting paint chips more coarsely. Which conclusion best follows?",
    mcOptions: [
      {
        text: "Sorting is too subjective to connect to which words a group has.",
        credit: 0,
      },
      {
        text: "They seem to notice ice differences more.",
        credit: 0.3,
      },
      {
        text: "A rich vocabulary in a domain likely reflects and reinforces fine attention there, so people carve up things they have words for more sharply. Test whether outsiders trained on the ice words start sorting ice more finely, whether the group's color sorting improves when given color labels, and whether sorting sharpness tracks each person's vocabulary size in that domain.",
        credit: 1.0,
      },
      {
        text: "Their vocabulary probably shapes their sorting; we could test more members.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'vocabulary sharpens attention' lead from the rival 'they just have more life experience with ice, words aside,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: teach outsiders the specific ice words (without extra ice experience) and see whether their sorting becomes finer — my lead predicts the labels alone improve discrimination. It is refuted if word-trained outsiders sort no better and only people with years of ice exposure do well, showing experience rather than vocabulary drives the effect.",
      yieldAnchors: [
        "The group has many words for snow and ice",
        "They sort icy landscapes into finer categories than researchers",
        "They sort paint chips more coarsely",
      ],
      riskAnchors: [
        "Outsiders trained on the ice words sort ice more finely",
        "The group's color sorting improves when given color labels",
        "Sorting sharpness tracks each person's vocabulary size",
      ],
      defeatedBy: [
        "Only hands-on ice experience, not words, improves sorting",
        "Vocabulary is unrelated to how finely people sort",
      ],
    },
    correctAnswer:
      "A rich vocabulary in a domain likely reflects and reinforces fine attention there, so people carve up things they have words for more sharply. Test whether outsiders trained on the ice words start sorting ice more finely, whether the group's color sorting improves when given color labels, and whether sorting sharpness tracks each person's vocabulary size in that domain.",
    explanation:
      "Top credit names a vocabulary-attention mechanism with three tests and a word-training test that names its refutation; 'too subjective to connect' refuses to lead.",
  },
  {
    itemType: "hybrid",
    prompt:
      "People across unrelated languages tend to guess that a rounded blob is called 'bouba' and a spiky shape 'kiki,' matching far above chance — even young children who can't yet read do this. Which lead is strongest?",
    mcOptions: [
      {
        text: "Sound-to-meaning matching is random, so the agreement is just coincidence.",
        credit: 0,
      },
      {
        text: "The mind probably has built-in links between certain speech sounds and shapes or sensations, so word forms aren't entirely arbitrary. Test whether the bouba/kiki match holds in pre-literate toddlers, whether it survives across languages with very different sound systems, and whether real words in the world's languages show the predicted sound-shape leanings above chance.",
        credit: 1.0,
      },
      {
        text: "People seem to agree on bouba and kiki.",
        credit: 0.3,
      },
      {
        text: "Sounds probably connect to shapes; we could test more people.",
        credit: 0.6,
      },
    ],
    writtenRubric: {
      prompt:
        "In two sentences, name the single cheapest observation that would most distinguish your 'built-in sound–shape links' lead from the rival 'people just learned these associations from their shared culture,' and say what result would refute your lead.",
      modelAnswer:
        "Cheapest test: run the bouba/kiki task with toddlers too young to read and with speakers of languages that have no cultural contact — my lead predicts above-chance matching everywhere, before culture could teach it. It is refuted if only literate adults from connected cultures show the effect while young children and isolated groups choose at chance, pointing to learning rather than a built-in link.",
      yieldAnchors: [
        "People match rounded shapes to 'bouba'",
        "People match spiky shapes to 'kiki'",
        "The match holds across unrelated languages above chance",
      ],
      riskAnchors: [
        "Pre-literate toddlers show the same match",
        "It survives across very different sound systems",
        "Real words show the predicted sound-shape leanings",
      ],
      defeatedBy: [
        "Only culturally connected literate adults show it",
        "Sound and shape are matched purely at random",
      ],
    },
    correctAnswer:
      "The mind probably has built-in links between certain speech sounds and shapes or sensations, so word forms aren't entirely arbitrary. Test whether the bouba/kiki match holds in pre-literate toddlers, whether it survives across languages with very different sound systems, and whether real words in the world's languages show the predicted sound-shape leanings above chance.",
    explanation:
      "Full credit names sound symbolism as a mechanism with three tests and a toddler/cross-language test that names its refutation; 'just coincidence' is defeated by the above-chance, cross-language agreement.",
  },
];

const written: HomeworkItem[] = [
  {
    itemType: "written",
    prompt:
      "A parent notices that their toddler, who used to correctly say 'I broke it,' has started saying 'I breaked it' and 'I builded a tower' for several weeks. The parent worries the child's English is getting worse. In one paragraph, propose the strongest conclusion about what's happening in the child's mind and describe how you would test it.",
    writtenRubric: {
      modelAnswer:
        "The strongest conclusion is that the child's language is not getting worse but getting more systematic: she has extracted the regular 'add -ed for past tense' rule and is now over-applying it to verbs she once produced correctly by memory, a temporary stage called overregularization. This commits to a mechanism — rule-learning replacing rote memory — and predicts checkable things: she should over-apply -ed to brand-new made-up verbs she's never heard, the errors should appear across many irregular verbs at once rather than one, and the mistakes should fade gradually as she re-learns each exception while keeping the rule. I would test it by teaching her a nonsense verb like 'to gling' and asking what happened yesterday (predicting 'glinged'), by tracking whether several irregulars regress together, and by checking over months whether correct irregular forms return without the regular rule disappearing.",
      yieldAnchors: [
        "She used to say 'broke' correctly",
        "She now says 'breaked' and 'builded'",
        "The change has lasted several weeks",
      ],
      riskAnchors: [
        "She over-applies -ed to a brand-new made-up verb",
        "Several irregular verbs regress at the same time",
        "Correct irregular forms return gradually without losing the rule",
      ],
      defeatedBy: [
        "Her language is genuinely deteriorating",
        "She is simply copying an adult who talks this way",
        "Nothing can be said without testing many more children",
      ],
    },
    correctAnswer:
      "The strongest conclusion is that the child's language is not getting worse but getting more systematic: she has extracted the regular 'add -ed for past tense' rule and is now over-applying it to verbs she once produced correctly by memory, a temporary stage called overregularization. This commits to a mechanism — rule-learning replacing rote memory — and predicts checkable things: she should over-apply -ed to brand-new made-up verbs she's never heard, the errors should appear across many irregular verbs at once rather than one, and the mistakes should fade gradually as she re-learns each exception while keeping the rule. I would test it by teaching her a nonsense verb like 'to gling' and asking what happened yesterday (predicting 'glinged'), by tracking whether several irregulars regress together, and by checking over months whether correct irregular forms return without the regular rule disappearing.",
    explanation:
      "The cautious 'we can't say without many more children' and the defeated 'her language is deteriorating' both score low; top credit goes to the rule-extraction conclusion that names a mechanism and a made-up-verb test that could refute it.",
  },
  {
    itemType: "written",
    prompt:
      "A researcher works with two groups: one speaks a language with separate words for 'light blue' and 'dark blue,' the other (English) uses 'blue' for both. In a fast same/different task with colored squares, the two-word group is quicker to spot a difference right at the light/dark blue line, but only when they aren't repeating numbers aloud during the task. In one paragraph, propose the strongest conclusion and describe how you would test it.",
    writtenRubric: {
      modelAnswer:
        "The strongest conclusion is that language gives a small, online perceptual boost at category boundaries by sharpening attention there — but the boost depends on language being available, which is why repeating numbers aloud (a verbal load) erases it. This commits to a specific mechanism (label-driven attention used in the moment, not a permanent rewiring of the eye) and predicts checkable things: the advantage should appear only at the light/dark boundary and not at arbitrary points within a category, it should return as soon as the verbal load is removed, and it should be larger in the visual field that feeds the language-dominant left hemisphere. I would test it by comparing boundary versus within-category pairs, by toggling the verbal-interference task on and off, and by presenting squares to the left versus right visual field to see whether the effect is stronger on the language-linked side.",
      yieldAnchors: [
        "The two-word group is faster right at the light/dark blue line",
        "English speakers show no such edge there",
        "The advantage disappears under a verbal (number-repeating) load",
      ],
      riskAnchors: [
        "The boost appears only at the category boundary, not within a category",
        "It returns when the verbal load is removed",
        "It is stronger in the left-hemisphere-linked visual field",
      ],
      defeatedBy: [
        "Language permanently rewires the eye so the effect should survive verbal load",
        "Language has no effect on color perception at all",
        "Nothing can be concluded from a reaction-time difference",
      ],
    },
    correctAnswer:
      "The strongest conclusion is that language gives a small, online perceptual boost at category boundaries by sharpening attention there — but the boost depends on language being available, which is why repeating numbers aloud (a verbal load) erases it. This commits to a specific mechanism (label-driven attention used in the moment, not a permanent rewiring of the eye) and predicts checkable things: the advantage should appear only at the light/dark boundary and not at arbitrary points within a category, it should return as soon as the verbal load is removed, and it should be larger in the visual field that feeds the language-dominant left hemisphere. I would test it by comparing boundary versus within-category pairs, by toggling the verbal-interference task on and off, and by presenting squares to the left versus right visual field to see whether the effect is stronger on the language-linked side.",
    explanation:
      "Both the overreach ('language permanently rewires the eye') and the dodge ('nothing can be concluded') score low; top credit goes to the online-attention conclusion that explains the verbal-load result and names tests that could refute it.",
  },
  {
    itemType: "written",
    prompt:
      "At a new school for deaf children who arrived with no shared language, teachers report that the very youngest students have begun signing to each other with consistent word order and grammatical markers, and that each new wave of young children signs in a more structured, rule-bound way than the older students who came before them. In one paragraph, propose the strongest conclusion about the mind and describe how you would test it.",
    writtenRubric: {
      modelAnswer:
        "The strongest conclusion is that the human mind comes equipped to build grammatical structure, so when young learners are given even unstructured raw material they spontaneously impose rules — and because this capacity is strongest in early childhood, each younger cohort adds more structure than the older signers could. This commits to a mechanism (a learner-driven, age-sensitive structuring ability rather than copying) and predicts checkable things: the grammatical regularities should originate with the youngest children and not the adults, later cohorts should systematically out-structure earlier ones on the same tasks, and the same emergence pattern should recur in other independently formed deaf communities. I would test it by tracing which signers introduced each grammatical feature, by comparing structure across cohorts entering at the same age, and by checking whether newly forming sign communities elsewhere show the identical youngest-drives-structure pattern.",
      yieldAnchors: [
        "The children arrived with no shared language",
        "The youngest sign with consistent grammar",
        "Each younger cohort is more structured than the older one",
      ],
      riskAnchors: [
        "Grammatical features originate with the youngest children, not adults",
        "Later cohorts out-structure earlier ones on the same tasks",
        "The same pattern recurs in other new deaf communities",
      ],
      defeatedBy: [
        "The children simply copied structure from hearing adults",
        "Grammar requires an existing structured model to learn from",
        "One community is too unusual to conclude anything",
      ],
    },
    correctAnswer:
      "The strongest conclusion is that the human mind comes equipped to build grammatical structure, so when young learners are given even unstructured raw material they spontaneously impose rules — and because this capacity is strongest in early childhood, each younger cohort adds more structure than the older signers could. This commits to a mechanism (a learner-driven, age-sensitive structuring ability rather than copying) and predicts checkable things: the grammatical regularities should originate with the youngest children and not the adults, later cohorts should systematically out-structure earlier ones on the same tasks, and the same emergence pattern should recur in other independently formed deaf communities. I would test it by tracing which signers introduced each grammatical feature, by comparing structure across cohorts entering at the same age, and by checking whether newly forming sign communities elsewhere show the identical youngest-drives-structure pattern.",
    explanation:
      "The defeated 'copied from adults' and the dodge 'too unusual to conclude' score low; top credit goes to the learner-driven structuring conclusion that names a mechanism and a cohort-tracing test that could refute it.",
  },
  {
    itemType: "written",
    prompt:
      "Speakers of a language that describes all locations by compass direction (instead of 'left/right') are tested in an unfamiliar building with the windows covered. After being led on a winding path, they can still point accurately back toward their starting town, while visiting researchers who speak a left/right language are badly disoriented. In one paragraph, propose the strongest conclusion and describe how you would test it.",
    writtenRubric: {
      modelAnswer:
        "The strongest conclusion is that having to specify compass directions in every sentence forces these speakers to continuously track their heading, building a habitual 'mental compass' that keeps working even without visible landmarks — so the language habit trains a real cognitive skill rather than reflecting a fixed inborn talent. This commits to a mechanism (constant directional encoding as ongoing training) and predicts checkable things: the advantage should hold when speakers are spun around indoors with no landmarks, children should acquire it gradually as they master the direction words, and left/right speakers given sustained practice describing the world in compass terms should improve toward the same level. I would test it by running disorientation trials with landmarks removed, by measuring children's pointing accuracy against their command of the direction terms, and by training a group of left/right speakers in compass description for several weeks and retesting them.",
      yieldAnchors: [
        "Their language uses compass directions, not left/right",
        "They point accurately home after a winding path with windows covered",
        "Left/right-speaking researchers are badly disoriented",
      ],
      riskAnchors: [
        "The advantage survives being spun around indoors with no landmarks",
        "Children gain it as they master the direction words",
        "Trained left/right speakers improve toward the same level",
      ],
      defeatedBy: [
        "The skill is a fixed inborn talent unrelated to language",
        "They were simply using visible landmarks",
        "Spatial ability is too personal to link to language at all",
      ],
    },
    correctAnswer:
      "The strongest conclusion is that having to specify compass directions in every sentence forces these speakers to continuously track their heading, building a habitual 'mental compass' that keeps working even without visible landmarks — so the language habit trains a real cognitive skill rather than reflecting a fixed inborn talent. This commits to a mechanism (constant directional encoding as ongoing training) and predicts checkable things: the advantage should hold when speakers are spun around indoors with no landmarks, children should acquire it gradually as they master the direction words, and left/right speakers given sustained practice describing the world in compass terms should improve toward the same level. I would test it by running disorientation trials with landmarks removed, by measuring children's pointing accuracy against their command of the direction terms, and by training a group of left/right speakers in compass description for several weeks and retesting them.",
    explanation:
      "The dodge 'too personal to link to language' and the defeated 'they just used landmarks' score low; top credit goes to the habitual-encoding conclusion that names a training mechanism and a learnability test that could refute it.",
  },
  {
    itemType: "written",
    prompt:
      "An immigrant family has two children: one arrived at age five, the other at age fifteen. Ten years later, both have lived in the new country the same length of time and use the new language daily, yet the younger sibling speaks it without an accent and with flawless grammar, while the older one still has a noticeable accent and makes consistent grammatical errors. In one paragraph, propose the strongest conclusion and describe how you would test it.",
    writtenRubric: {
      modelAnswer:
        "The strongest conclusion is that there is a sensitive period for language: the brain's language circuits are most plastic in early childhood and gradually lose that flexibility, so age of first exposure — not total years of practice — sets the ceiling on accent and grammar, which is why the younger sibling reached native-like mastery and the older one did not. This commits to a mechanism (declining neural plasticity with age) and predicts checkable things: across many immigrants, final proficiency should track arrival age far more tightly than years of practice, the accent/grammar gap should hold even when the late arrivals have had more total exposure, and brain imaging should show late learners recruiting different or extra regions to process the language. I would test it by plotting proficiency against age-of-arrival versus years-of-use in a large sample, by matching pairs on total exposure while varying arrival age, and by comparing the brain activity of early and late learners doing the same grammar task.",
      yieldAnchors: [
        "Both siblings have lived in the country the same length of time",
        "Both use the new language daily",
        "The younger arrival is native-like; the older one has an accent and grammar errors",
      ],
      riskAnchors: [
        "Proficiency tracks arrival age more tightly than years of practice",
        "The gap holds even when late arrivals have more total exposure",
        "Late learners show different brain processing for the language",
      ],
      defeatedBy: [
        "Practice time, not arrival age, fully explains the difference",
        "The older sibling simply tried less hard",
        "Language ability is too variable to blame the age of arrival",
      ],
    },
    correctAnswer:
      "The strongest conclusion is that there is a sensitive period for language: the brain's language circuits are most plastic in early childhood and gradually lose that flexibility, so age of first exposure — not total years of practice — sets the ceiling on accent and grammar, which is why the younger sibling reached native-like mastery and the older one did not. This commits to a mechanism (declining neural plasticity with age) and predicts checkable things: across many immigrants, final proficiency should track arrival age far more tightly than years of practice, the accent/grammar gap should hold even when the late arrivals have had more total exposure, and brain imaging should show late learners recruiting different or extra regions to process the language. I would test it by plotting proficiency against age-of-arrival versus years-of-use in a large sample, by matching pairs on total exposure while varying arrival age, and by comparing the brain activity of early and late learners doing the same grammar task.",
    explanation:
      "The dodge 'too variable to blame age' and the unfalsifiable 'he just tried less hard' score low; top credit goes to the sensitive-period conclusion that names a plasticity mechanism and an age-versus-practice test that could refute it.",
  },
];

export const section: SectionContent = {
  slug: "language-and-thought",
  title: "Language and Thought: The Code Inside Your Head",
  weekNumber: 1,
  blurb:
    "Language is more than words — it's a structured code your mind builds almost automatically. We look at how children crack that code, what's shared across all human languages, and whether the language you speak shapes the way you think.",
  lectureTitle:
    "1.5 Language and Thought: the code inside your head",
  body: `# Language and Thought: The Code Inside Your Head

Every human group has language. No one teaches a baby grammar with lessons, yet by age four or five almost every child controls a system more intricate than anything we can fully write down. How does the mind pull this off — and does the particular language you speak change how you think? These are two of the biggest questions in cognitive science.

## Language is structure, not just words

A language isn't a pile of words; it's a set of rules for combining them. From a small vocabulary and a handful of patterns, you can produce sentences no one has ever said before, and other speakers understand them instantly. That creativity is the clue: you can't be storing every sentence, because most are brand new. You must be running rules. The strongest evidence comes from kids' mistakes — a toddler who says "goed" or "foots" was never taught those words. She couldn't have copied them; she generated them by over-applying a rule she extracted on her own.

## How children crack the code

Children learn language astonishingly fast from messy, incomplete input, and adults rarely drill them on grammar. This gap between thin input and rich knowledge — sometimes called the "poverty of the stimulus" — suggests the mind brings built-in expectations about how languages can work, narrowing the guesses a learner has to make. Babies help themselves, too: long before they speak, they track which sounds tend to follow which others, using raw statistics to slice a stream of speech into word-like chunks. And the famous "wug test" shows the payoff — shown one "wug," a preschooler confidently says "two wugs," applying a plural rule to a word she's never heard.

## What's shared across all languages

Beneath their surface differences, human languages share deep features: they all build phrases, mark who-did-what-to-whom, and allow structures nested inside structures. Strong evidence that this capacity lives in the learner comes from deaf children with no shared language who spontaneously invent sign systems with real grammar — and the youngest children add the most structure. Brain studies point the same way: signed and spoken languages recruit many of the same left-hemisphere regions, suggesting the brain's language system cares about abstract grammar and meaning, not whether you use your mouth or your hands.

## Timing matters: the sensitive period

The ability to master a language seems to have a window. Children who start a language early usually become fully fluent; those who start after puberty almost always keep an accent and stumble on fine grammar — even with the same years of practice. This points to a sensitive period when language circuits are especially plastic and later stiffen. The key test is that outcome tracks the age you *started*, not how long you've practiced.

## Does language shape thought?

Here's the controversial part. Some patterns suggest your language can nudge your thinking: speakers with two words for "blue" spot that boundary a little faster; speakers whose language uses compass directions keep an uncanny mental compass; grammatical gender can color how people describe objects. But culture and experience are always lurking as rival explanations, so the careful move is to test within bilinguals, match cultures, or train people on new words and see if the effect follows. Most evidence supports a modest claim — language shapes thought at the edges, sharpening attention and habits — rather than the bold claim that it traps you.

## In the real world

Imagine you notice that friends who grew up bilingual seem quicker to switch between tasks and tune out distractions. The dodge is "minds are too different to say anything." The stronger conclusion names a mechanism: constantly keeping one language active while suppressing the other trains the brain's general control system. Notice how much that opens up — check whether the people who switch languages most show the biggest control advantage, whether the effect survives matching family background, and whether monolinguals trained on heavy task-switching catch up. Three cheap tests, each able to prove the idea wrong. That's the move this course rewards: commit to the richest conclusion the evidence supports, and name the test that could refute it.`,
  homework: {
    mcq,
    hybrid,
    written,
  },
};
